CREATE DATABASE IF NOT EXISTS CarCompany;
USE CarCompany;
/*DROP DATABASE carCompany;
*/
CREATE TABLE IF NOT EXISTS Dealership (
	Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nombre NVARCHAR(45),
    PhoneNumber NVARCHAR(25),
    Address NVARCHAR(25)
);


CREATE TABLE Orden (
	Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DealershipId INT NOT NULL,
	FOREIGN KEY(DealershipId) REFERENCES Dealership(Id),
	fecha DATETIME
);

CREATE TABLE IF NOT EXISTS Model(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Nombre NVARCHAR(45)
);
CREATE TABLE Order_Detail (
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT ,
	OrderId INT ,
	ModelId INT ,
	FOREIGN KEY (OrderId) REFERENCES Orden(Id),
	FOREIGN KEY (ModelId) REFERENCES Model(Id)
);

CREATE TABLE IF NOT EXISTS Car (
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Patent NVARCHAR(45),
    ModelId  INT ,
    OrderId INT,
    FinishDate DATETIME,
    
    FOREIGN KEY (ModelId) REFERENCES Model(Id),
	FOREIGN KEY (OrderId) REFERENCES Orden(Id)
);

CREATE TABLE IF NOT EXISTS AssemblyLine(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ModelId INT,
    FOREIGN KEY (ModelId) REFERENCES Model(Id)
);

CREATE TABLE IF NOT EXISTS Task(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Nombre NVARCHAR(45)
);

CREATE TABLE IF NOT EXISTS Workstation(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    AssemblyLineId INT,
    TaskId INT,
    Orden INT,
    FOREIGN KEY(AssemblyLineId) REFERENCES AssemblyLine(Id),
    FOREIGN KEY(TaskId) REFERENCES Task(Id)
);
CREATE TABLE IF NOT EXISTS Car_Workstation(
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CarId INT ,
    WorkstationId INT ,
    StartDate DATETIME,
    FinishDate DATETIME,
    FOREIGN KEY (CarId) REFERENCES Car(Id),
    FOREIGN KEY (WorkstationId) REFERENCES Workstation(Id)
);


CREATE TABLE IF NOT EXISTS Supplier (
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255),
    Adrress VARCHAR(255),
    PhoneNumber VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Purchase (
	Id INT PRIMARY KEY AUTO_INCREMENT,
    SupplierId INT,
    Date DATETIME,
    
    FOREIGN KEY (SupplierId) REFERENCES Supplier(Id)
);

CREATE TABLE IF NOT EXISTS Supplie(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Nombre NVARCHAR(45),
    Prince DECIMAL UNSIGNED

);

CREATE TABLE IF NOT EXISTS Purchase_Supplie (
	Id INT PRIMARY KEY AUTO_INCREMENT,
    PurchaseId INT,
    SupplieId INT,
    Cant INT,
    Price DECIMAL UNSIGNED,
    
    FOREIGN KEY (PurchaseId) REFERENCES Purchase(Id),
    FOREIGN KEY (SupplieId) REFERENCES Supplie(Id)
);

CREATE TABLE IF NOT EXISTS Task_Supplie (
	Id INT PRIMARY KEY AUTO_INCREMENT,
    TaskId INT,
    SupplieId INT,
    Cant INT,
    FOREIGN KEY (TaskId) REFERENCES Task(Id),
    FOREIGN KEY (SupplieId) REFERENCES Supplie(Id)
);